apiVersion: v1
kind: Service
metadata:
  name: boundary-controller-external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: boundary-controller
