apiVersion: v1
kind: Service
metadata:
  name: hashibank-external
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hashibank
  sessionAffinity: None
  type: LoadBalancer
