apiVersion: v1
kind: Service
metadata:
  name: boundary-worker-external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9202
      protocol: TCP
  selector:
    app: boundary-worker
