apiVersion: v1
kind: Service
metadata:
  name: vault-external
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 8200
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  sessionAffinity: None
  type: LoadBalancer
