apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: hashibank
  name: hashibank
  namespace: app
spec:
  containers:
  - image: jamiewri/hashibank:0.0.3
    name: hashibank
    args:
      - -dev
    ports:
    - name: web
      containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
