apiVersion: v1
kind: Service
metadata:
  name: boundary-controller-internal
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9200
      targetPort: 9200
    - name: cluster
      port: 9201
      targetPort: 9201
    - name: data
      port: 9202
      targetPort: 9202
  selector:
    app: boundary-controller
